default_job = "clippy-all"
env.CARGO_TERM_COLOR = "always"

[jobs.clippy-all]
command = ["cargo", "clippy", "--all-targets"]
need_stdout = false

[jobs.run]
command = [
    "cargo", "run",
    # "--", ""
]
need_stdout = true
allow_warnings = true
background = true

[jobs.run-long]
command = [
    "cargo", "run",
    # "--", ""
]
need_stdout = true
allow_warnings = true
background = false
on_change_strategy = "kill_then_restart"
# kill = ["pkill", "-TERM", "-P"]'

[keybindings]
# alt-m = "job:my-job"
c = "job:clippy-all"
