name: Publish Crate

permissions:
  contents: read
on:
  workflow_call:
    inputs:
      plan:
        required: true
        type: string

jobs:
  cargo-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Get Auth Token
        uses: rust-lang/crates-io-auth-action@v1
        id: auth
      - name: Publish to crates.io
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
